---
output:
  html_document:
    fig_caption: yes
    theme: spacelab
    toc: no
---
# **plots of variant distribution along chromosome length**

Load libraries and the data
```{r setup, include=FALSE}
# load the required libraries and functions
library(knitr)
library(markdown)
#opts_chunk$set(dev = 'pdf')
library(reshape2)

# source custom R functions
source('~/git-hub-repos/shyamrallapalli/mutations_hts_noref/lib/ggplot_theme.R')
source('~/git-hub-repos/shyamrallapalli/mutations_hts_noref/lib/zero_ratio_adj.R')
source('~/git-hub-repos/shyamrallapalli/mutations_hts_noref/lib/lm_eqn_plot.R')

```

...     

...  		

#### 10,000 bp grouping of whole genome

```{r 10kb, echo=FALSE, fig.width=12, fig.height=6}
tenkb <- read.delim(file="per-10000bp-filtered_hsty_mutant.vcf.txt", header = TRUE)
tenkb <- re_zero_ratio(tenkb, 0.01)
melted <- melt(tenkb, id.vars = "position")
ggplot(data=melted, aes(x=position, y=value)) + geom_bar(stat="identity", colour="#E69F00", fill="#E69F00") +
  facet_grid(variable ~ ., scales = "free") +
  scale_y_sqrt() + labs(y=NULL, main="genome in 10 KB fragment chunks") + mytheme +
  geom_vline(xintercept = as.numeric(45071092), size=0.5)

```


...		

...  	


#### 50,000 bp grouping of whole genome

```{r 50kb, echo=FALSE, fig.width=12, fig.height=6}
tenkb <- read.delim(file="per-50000bp-filtered_hsty_mutant.vcf.txt", header = TRUE)
tenkb <- re_zero_ratio(tenkb, 0.01)
melted <- melt(tenkb, id.vars = "position")
ggplot(data=melted, aes(x=position, y=value)) + geom_bar(stat="identity", colour="#E69F00", fill="#E69F00") +
  facet_grid(variable ~ ., scales = "free") +
  scale_y_sqrt() + labs(y=NULL, main="genome in 50 KB fragment chunks") + mytheme +
  geom_vline(xintercept = as.numeric(45071092), size=0.5)

```


...		

...  	


#### 100,000 bp grouping of whole genome

```{r 100kb, echo=FALSE, fig.width=12, fig.height=6}
tenkb <- read.delim(file="per-100000bp-filtered_hsty_mutant.vcf.txt", header = TRUE)
tenkb <- re_zero_ratio(tenkb, 0.01)
melted <- melt(tenkb, id.vars = "position")
ggplot(data=melted, aes(x=position, y=value)) + geom_bar(stat="identity", colour="#E69F00", fill="#E69F00") +
  facet_grid(variable ~ ., scales = "free") +
  scale_y_sqrt() + labs(y=NULL, main="genome in 100 KB fragment chunks") + mytheme +
  geom_vline(xintercept = as.numeric(45071092), size=0.5)

```


...		

...  	


#### 500,000 bp grouping of whole genome

```{r 500kb, echo=FALSE, fig.width=12, fig.height=6}
tenkb <- read.delim(file="per-500000bp-filtered_hsty_mutant.vcf.txt", header = TRUE)
tenkb <- re_zero_ratio(tenkb, 0.01)
melted <- melt(tenkb, id.vars = "position")
ggplot(data=melted, aes(x=position, y=value)) + geom_bar(stat="identity", colour="#E69F00", fill="#E69F00") +
  facet_grid(variable ~ ., scales = "free") +
  scale_y_sqrt() + labs(y=NULL, main="genome in 500 KB fragment chunks") + mytheme +
  geom_vline(xintercept = as.numeric(45071092), size=0.5)

```


...		

...  	


#### 1,000,000 bp grouping of whole genome

```{r 1Mb, echo=FALSE, fig.width=12, fig.height=6}
tenkb <- read.delim(file="per-1000000bp-filtered_hsty_mutant.vcf.txt", header = TRUE)
tenkb <- re_zero_ratio(tenkb, 0.01)
melted <- melt(tenkb, id.vars = "position")
ggplot(data=melted, aes(x=position, y=value)) + geom_bar(stat="identity", colour="#E69F00", fill="#E69F00") +
  facet_grid(variable ~ ., scales = "free") +
  scale_y_sqrt() + labs(y=NULL, main="genome in 1 MB fragment chunks") + mytheme +
  geom_vline(xintercept = as.numeric(45071092), size=0.5)

```


...		

...  	


#### 5,000,000 bp grouping of whole genome

```{r 5Mb, echo=FALSE, fig.width=12, fig.height=6}
tenkb <- read.delim(file="per-5000000bp-filtered_hsty_mutant.vcf.txt", header = TRUE)
tenkb <- re_zero_ratio(tenkb, 0.01)
melted <- melt(tenkb, id.vars = "position")
ggplot(data=melted, aes(x=position, y=value)) + geom_bar(stat="identity", colour="#E69F00", fill="#E69F00") +
  facet_grid(variable ~ ., scales = "free") +
  scale_y_sqrt() + labs(y=NULL, main="genome in 5 MB fragment chunks") + mytheme +
  geom_vline(xintercept = as.numeric(45071092), size=0.5)

```


...		

...  	


#### 10,000,000 bp grouping of whole genome

```{r 10Mb, echo=FALSE, fig.width=12, fig.height=6}
tenkb <- read.delim(file="per-10000000bp-filtered_hsty_mutant.vcf.txt", header = TRUE)
tenkb <- re_zero_ratio(tenkb, 0.01)
melted <- melt(tenkb, id.vars = "position")
ggplot(data=melted, aes(x=position, y=value)) + geom_bar(stat="identity", colour="#E69F00", fill="#E69F00") +
  facet_grid(variable ~ ., scales = "free") +
  scale_y_sqrt() + labs(y=NULL, main="genome in 10 MB fragment chunks") + mytheme +
  geom_vline(xintercept = as.numeric(45071092), size=0.5)

```


...		

...  	


#### density plot for hm and ht

```{r genome, echo=FALSE, fig.width=12, fig.height=6}
infile <- read.delim(file="varposn-genome-filtered_hsty_mutant.vcf.txt", header = TRUE)
ggplot(data=infile, aes(x=position, colour=type)) + geom_density(adjust=1/10) +
  geom_vline(xintercept = as.numeric(45071092), size=0.5) +
  scale_y_sqrt() + labs(y=NULL, main="genome wide snp density") + mytheme + theme(legend.position=c(0.9,0.9))

```



